package Vista;

import java.time.Clock;
import javax.swing.JFrame;

public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setSize(800, 700);
        this.setLocationRelativeTo(null);
        this.setTitle("Universidad ULP");
        this.setResizable(false);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMAlumno = new javax.swing.JMenu();
        jMIFormAlumno = new javax.swing.JMenuItem();
        jMMateria = new javax.swing.JMenu();
        jMIFormMateria = new javax.swing.JMenuItem();
        jMAdministracion = new javax.swing.JMenu();
        jMeIInscripciones = new javax.swing.JMenuItem();
        jMINotas = new javax.swing.JMenuItem();
        jMConsultas = new javax.swing.JMenu();
        jMIAlumMate = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 821, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jMAlumno.setText("Alumno");

        jMIFormAlumno.setText("Formulario de Alumno");
        jMIFormAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIFormAlumnoActionPerformed(evt);
            }
        });
        jMAlumno.add(jMIFormAlumno);

        jMenuBar1.add(jMAlumno);

        jMMateria.setText("Materia");

        jMIFormMateria.setText("Formulario de materia");
        jMIFormMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIFormMateriaActionPerformed(evt);
            }
        });
        jMMateria.add(jMIFormMateria);

        jMenuBar1.add(jMMateria);

        jMAdministracion.setText("Administracion");

        jMeIInscripciones.setText("Manejo de inscripciones");
        jMeIInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMeIInscripcionesActionPerformed(evt);
            }
        });
        jMAdministracion.add(jMeIInscripciones);

        jMINotas.setText("Manipulacion de notas");
        jMINotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMINotasActionPerformed(evt);
            }
        });
        jMAdministracion.add(jMINotas);

        jMenuBar1.add(jMAdministracion);

        jMConsultas.setText("Consultas");

        jMIAlumMate.setText("Alumnos por materia");
        jMIAlumMate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAlumMateActionPerformed(evt);
            }
        });
        jMConsultas.add(jMIAlumMate);

        jMenuBar1.add(jMConsultas);

        jMSalir.setText("Salir");
        jMSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIFormAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIFormAlumnoActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        GestionAlumno gestionAlumno = new GestionAlumno();
        jDesktopPane1.add(gestionAlumno);
        gestionAlumno.setVisible(true);
    }//GEN-LAST:event_jMIFormAlumnoActionPerformed

    private void jMIFormMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIFormMateriaActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        GestionMateria gestionMateria = new GestionMateria();
        jDesktopPane1.add(gestionMateria);
        gestionMateria.setVisible(true);
    }//GEN-LAST:event_jMIFormMateriaActionPerformed

    private void jMeIInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMeIInscripcionesActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        Inscripciones inscripciones = new Inscripciones();
        jDesktopPane1.add(inscripciones);
        inscripciones.setVisible(true);
    }//GEN-LAST:event_jMeIInscripcionesActionPerformed

    private void jMINotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMINotasActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        ActualizacionNotas actualizacionNotas = new ActualizacionNotas();
        jDesktopPane1.add(actualizacionNotas);
        actualizacionNotas.setVisible(true);
    }//GEN-LAST:event_jMINotasActionPerformed

    private void jMIAlumMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAlumMateActionPerformed
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        ListaMateria listaMateria = new ListaMateria();
        jDesktopPane1.add(listaMateria);
        listaMateria.setVisible(true);
    }//GEN-LAST:event_jMIAlumMateActionPerformed

    private void jMSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMAdministracion;
    private javax.swing.JMenu jMAlumno;
    private javax.swing.JMenu jMConsultas;
    private javax.swing.JMenuItem jMIAlumMate;
    private javax.swing.JMenuItem jMIFormAlumno;
    private javax.swing.JMenuItem jMIFormMateria;
    private javax.swing.JMenuItem jMINotas;
    private javax.swing.JMenu jMMateria;
    private javax.swing.JMenu jMSalir;
    private javax.swing.JMenuItem jMeIInscripciones;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
